### ISSUE TITLE
How to read the results?

### ISSUE THREAD

**Issue by jameszhou-gl** [JoSangYoung/Official-POEM#2]
Hi author, thanks for  your exciting work.
I'm writing to make sure how to read the results accurately.

+------------+
| Selection  | 
+------------+
|   oracle   | 
|    iid     |  
|    last    |   
| last (inD) | 
| iid (inD)  |  
+------------+

So basically, we choose the Avg value with the row of iid, right?
Thanks a lot!

**Comment by JoSangYoung** [comment]
Hi! Thank you for having an interest in my work!

Yes, we chose the average value of iid. And the inD indicates the in-domain performance.
